name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node
      - run: npm install -g firebase-tools
      - run: firebase deploy --project workflows-test-13c0a --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WORKFLOWS_TEST_13C0A }}
